export const environment = {
  NEXT_PUBLIC_URL_PROD: process.env.NEXT_PUBLIC_FE_URL,
  NEXT_PUBLIC_URL: process.env.NEXT_PUBLIC_URL,
  PUBLIC_URL: process.env.PUBLIC_URL,
  NEXT_PUBLIC_LOCALSTORAGE_SECRET_KEY:
    process.env.NEXT_PUBLIC_LOCALSTORAGE_SECRET_KEY,
  NEXT_PUBLIC_IP_DATA_URL: process.env.NEXT_PUBLIC_IP_DATA_URL,
}
